export interface Races {
  faction: string;
  raceName: string;
  gender: string;
  imgPath: string;
  availableClasses: string[];
}

//Alliance Races
const humanM: Races = {
  faction: 'Alliance',
  raceName: 'Human',
  gender: 'Male',
  imgPath: '/assets/race-icons/human_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Paladin',
  ],
};
const humanF: Races = {
  faction: 'Alliance',
  raceName: 'Human',
  gender: 'Female',
  imgPath: '/assets/race-icons/human_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Paladin',
  ],
};
const dwarfM: Races = {
  faction: 'Alliance',
  raceName: 'Dwarf',
  gender: 'Male',
  imgPath: '/assets/race-icons/dwarf_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
    'Paladin',
  ],
};
const dwarF: Races = {
  faction: 'Alliance',
  raceName: 'Dwarf',
  gender: 'Female',
  imgPath: '/assets/race-icons/dwarf_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
    'Paladin',
  ],
};
const nightElfM: Races = {
  faction: 'Alliance',
  raceName: 'Night Elf',
  gender: 'Male',
  imgPath: '/assets/race-icons/night_elf_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Druid',
    'Demon Hunter',
  ],
};
const nightElfF: Races = {
  faction: 'Alliance',
  raceName: 'Night Elf',
  gender: 'Female',
  imgPath: '/assets/race-icons/night_elf_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Druid',
    'Demon Hunter',
  ],
};
const gnomeM: Races = {
  faction: 'Alliance',
  raceName: 'Gnome',
  gender: 'Male',
  imgPath: '/assets/race-icons/gnome_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const gnomeF: Races = {
  faction: 'Alliance',
  raceName: 'Gnome',
  gender: 'Female',
  imgPath: '/assets/race-icons/gnome_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const draeneiM: Races = {
  faction: 'Alliance',
  raceName: 'Draenei',
  gender: 'Male',
  imgPath: '/assets/race-icons/draenei_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Shaman',
    'Paladin',
  ],
};
const draeneiF: Races = {
  faction: 'Alliance',
  raceName: 'Draenei',
  gender: 'Female',
  imgPath: '/assets/race-icons/draenei_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Shaman',
    'Paladin',
  ],
};
const worgenM: Races = {
  faction: 'Alliance',
  raceName: 'Worgen',
  gender: 'Male',
  imgPath: '/assets/race-icons/worgen_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Druid',
  ],
};
const worgenF: Races = {
  faction: 'Alliance',
  raceName: 'Worgen',
  gender: 'Female',
  imgPath: '/assets/race-icons/worgen_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Druid',
  ],
};
const voidElfM: Races = {
  faction: 'Alliance',
  raceName: 'Void Elf',
  gender: 'Male',
  imgPath: '/assets/race-icons/void_elf_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const voidElfF: Races = {
  faction: 'Alliance',
  raceName: 'Void Elf',
  gender: 'Female',
  imgPath: '/assets/race-icons/void_elf_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const lightforgedM: Races = {
  faction: 'Alliance',
  raceName: 'Lightforged Draenei',
  gender: 'Male',
  imgPath: '/assets/race-icons/lightforged_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Paladin',
  ],
};
const lightforgedF: Races = {
  faction: 'Alliance',
  raceName: 'Lightforged Draenei',
  gender: 'Female',
  imgPath: '/assets/race-icons/lightforged_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Paladin',
  ],
};
const darkIronM: Races = {
  faction: 'Alliance',
  raceName: 'Dark Iron Dwarf',
  gender: 'Male',
  imgPath: '/assets/race-icons/dark_iron_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
    'Paladin',
  ],
};
const darkIronF: Races = {
  faction: 'Alliance',
  raceName: 'Dark Iron Dwarf',
  gender: 'Female',
  imgPath: '/assets/race-icons/dark_iron_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
    'Paladin',
  ],
};
const kultiranM: Races = {
  faction: 'Alliance',
  raceName: 'Kul Tiran Human',
  gender: 'Male',
  imgPath: '/assets/race-icons/kultiran_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
    'Druid',
  ],
};
const kultiranF: Races = {
  faction: 'Alliance',
  raceName: 'Kul Tiran Human',
  gender: 'Female',
  imgPath: '/assets/race-icons/kultiran_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
    'Druid',
  ],
};
const mechagnomeM: Races = {
  faction: 'Alliance',
  raceName: 'Mechagnome',
  gender: 'Male',
  imgPath: '/assets/race-icons/mechagnome_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const mechagnomeF: Races = {
  faction: 'Alliance',
  raceName: 'Mechagnome',
  gender: 'Female',
  imgPath: '/assets/race-icons/mechagnome_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const aPandarenM: Races = {
  faction: 'Alliance',
  raceName: 'Pandaren',
  gender: 'Male',
  imgPath: '/assets/race-icons/pandaren_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
  ],
};
const aPandarenF: Races = {
  faction: 'Alliance',
  raceName: 'Pandaren',
  gender: 'Female',
  imgPath: '/assets/race-icons/pandaren_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
  ],
};
//End of Alliance Races

export const allianceMales: Races[] = [
  humanM,
  dwarfM,
  nightElfM,
  gnomeM,
  draeneiM,
  worgenM,
  voidElfM,
  lightforgedM,
  darkIronM,
  kultiranM,
  mechagnomeM,
  aPandarenM,
];
export const allianceFemales: Races[] = [
  humanF,
  dwarF,
  nightElfF,
  gnomeF,
  draeneiF,
  worgenF,
  voidElfF,
  lightforgedF,
  darkIronF,
  kultiranF,
  mechagnomeF,
  aPandarenF,
];

//Horde Races
const orcM: Races = {
  faction: 'Horde',
  raceName: 'Orc',
  gender: 'Male',
  imgPath: '/assets/race-icons/orc_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
  ],
};
const orcF: Races = {
  faction: 'Horde',
  raceName: 'Orc',
  gender: 'Female',
  imgPath: '/assets/race-icons/orc_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
  ],
};
const undeadM: Races = {
  faction: 'Horde',
  raceName: 'Undead',
  gender: 'Male',
  imgPath: '/assets/race-icons/undead_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const undeadF: Races = {
  faction: 'Horde',
  raceName: 'Undead',
  gender: 'Female',
  imgPath: '/assets/race-icons/undead_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const taurenM: Races = {
  faction: 'Horde',
  raceName: 'Tauren',
  gender: 'Male',
  imgPath: '/assets/race-icons/tauren_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Priest',
    'Monk',
    'Shaman',
    'Paladin',
    'Druid',
  ],
};
const taurenF: Races = {
  faction: 'Horde',
  raceName: 'Tauren',
  gender: 'Female',
  imgPath: '/assets/race-icons/tauren_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Priest',
    'Monk',
    'Shaman',
    'Paladin',
    'Druid',
  ],
};
const trollM: Races = {
  faction: 'Horde',
  raceName: 'Troll',
  gender: 'Male',
  imgPath: '/assets/race-icons/troll_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
    'Druid',
  ],
};
const trollF: Races = {
  faction: 'Horde',
  raceName: 'Troll',
  gender: 'Female',
  imgPath: '/assets/race-icons/troll_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
    'Druid',
  ],
};
const bloodElfM: Races = {
  faction: 'Horde',
  raceName: 'Blood Elf',
  gender: 'Male',
  imgPath: '/assets/race-icons/blood_elf_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Paladin',
    'Demon Hunter',
  ],
};
const bloodElfF: Races = {
  faction: 'Horde',
  raceName: 'Blood Elf',
  gender: 'Female',
  imgPath: '/assets/race-icons/blood_elf_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Paladin',
    'Demon Hunter',
  ],
};
const goblinM: Races = {
  faction: 'Horde',
  raceName: 'Goblin',
  gender: 'Male',
  imgPath: '/assets/race-icons/goblin_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Rogue',
    'Warlock',
    'Shaman',
  ],
};
const goblinF: Races = {
  faction: 'Horde',
  raceName: 'Goblin',
  gender: 'Female',
  imgPath: '/assets/race-icons/goblin_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Rogue',
    'Warlock',
    'Shaman',
  ],
};
const nightborneM: Races = {
  faction: 'Horde',
  raceName: 'Nightborne',
  gender: 'Male',
  imgPath: '/assets/race-icons/nightborne_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const nightborneF: Races = {
  faction: 'Horde',
  raceName: 'Nightborne',
  gender: 'Female',
  imgPath: '/assets/race-icons/nightborne_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
  ],
};
const highmountainM: Races = {
  faction: 'Horde',
  raceName: 'Highmountain Tauren',
  gender: 'Male',
  imgPath: '/assets/race-icons/highmountain_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Monk',
    'Shaman',
    'Druid',
  ],
};
const highmountainF: Races = {
  faction: 'Horde',
  raceName: 'Highmountain Tauren',
  gender: 'Female',
  imgPath: '/assets/race-icons/highmountain_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Monk',
    'Shaman',
    'Druid',
  ],
};
const magharM: Races = {
  faction: 'Horde',
  raceName: "Mag'har Orc",
  gender: 'Male',
  imgPath: '/assets/race-icons/maghar_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
  ],
};
const magharF: Races = {
  faction: 'Horde',
  raceName: "Mag'har Orc",
  gender: 'Female',
  imgPath: '/assets/race-icons/maghar_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
  ],
};
const zandalariM: Races = {
  faction: 'Horde',
  raceName: 'Zandalari Troll',
  gender: 'Male',
  imgPath: '/assets/race-icons/zandalari_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
    'Paladin',
    'Druid',
  ],
};
const zandalariF: Races = {
  faction: 'Horde',
  raceName: 'Zandalari Troll',
  gender: 'Female',
  imgPath: '/assets/race-icons/zandalari_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
    'Paladin',
    'Druid',
  ],
};
const vulperaM: Races = {
  faction: 'Horde',
  raceName: 'Vulpera',
  gender: 'Male',
  imgPath: '/assets/race-icons/vulpera_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
  ],
};
const vulperaF: Races = {
  faction: 'Horde',
  raceName: 'Vulpera',
  gender: 'Female',
  imgPath: '/assets/race-icons/vulpera_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Warlock',
    'Shaman',
  ],
};
const hPandarenM: Races = {
  faction: 'Horde',
  raceName: 'Pandaren',
  gender: 'Male',
  imgPath: '/assets/race-icons/pandaren_male.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
  ],
};
const hPandarenF: Races = {
  faction: 'Horde',
  raceName: 'Pandaren',
  gender: 'Female',
  imgPath: '/assets/race-icons/pandaren_female.png',
  availableClasses: [
    'Warrior',
    'Hunter',
    'Death Knight',
    'Mage',
    'Priest',
    'Monk',
    'Rogue',
    'Shaman',
  ],
};

// End of Horde Races
export const hordeMales: Races[] = [
  orcM,
  undeadM,
  taurenM,
  trollM,
  bloodElfM,
  goblinM,
  nightborneM,
  highmountainM,
  magharM,
  zandalariM,
  vulperaM,
  hPandarenM,
];
export const hordeFemales: Races[] = [
  orcF,
  undeadF,
  taurenF,
  trollF,
  bloodElfF,
  goblinF,
  nightborneF,
  highmountainF,
  magharF,
  zandalariF,
  vulperaF,
  hPandarenF,
];
